---

-
  hosts: ubuntu

  tasks:
    - name: Configure MOTD
      copy:
        src: ./60-ansible-motd
        dest: /etc/update-motd.d/60-ansible-motd
          #mode: preserve
      when: ansible_distribution == "Ubuntu"
      notify: MOTD changed!

  handlers:
    - name: MOTD changed!
      debug:
        msg: The MOTD  was altered!
...
