---
-
  hosts: all

  tasks:
    - name: Ansible Jinja2 if elif
      debug:
        msg: > 
             --== Ansible Jinja2 if elif statement ==--

             {% if ansible_hostname == "ubuntu-c" %}
                      This is ubuntu-c
             {% elif ansible_hostname == "centos1" %}
                      This is centos1 with its modified SSH-Port!
             {% else %}
                      This is good old {{ ansible_hostname }}
             {% endif %}


...
