---
-
  hosts: centos
  user: root
  gather_facts: False

  vars:
    motd: "Welcome to CentOS Linux - Ansible Rocks\n"

  tasks:
    - name: Configure a MOTD
      copy:
        content: "{{ motd }}"
        dest: /etc/motd
      notify: MOTD changed

  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed!
...
