---
-
  hosts: linux
  gather_facts: True

  tasks:
    - name: Test hostvars with an ansible fact & collect ansible_port
      debug:
        msg: "{{ ansible_port | default('Default 22') }}"

    - name: Test groupvars
      debug:
        msg: "{{ ansible_user }}"
...